<?xml version="1.0" encoding="utf-8"?><Database Name="BDControlAsistencia" Class="CAsistenciaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=BDControlAsistencia;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BDControlAsistenciaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TAlumno" Member="TAlumno">
    <Type Name="TAlumno">
      <Column Name="IdAlumno" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TAlumno_TAsistencia" Member="TAsistencia" ThisKey="IdAlumno" OtherKey="IdAlumno" Type="TAsistencia" />
      <Association Name="TUsuario_TAlumno" Member="TUsuario" ThisKey="CodUsuario" OtherKey="CodUsuario" Type="TUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAsistencia" Member="TAsistencia">
    <Type Name="TAsistencia">
      <Column Name="IdAsistencia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdAlumno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TAlumno_TAsistencia" Member="TAlumno" ThisKey="IdAlumno" OtherKey="IdAlumno" Type="TAlumno" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAuxiliar" Member="TAuxiliar">
    <Type Name="TAuxiliar">
      <Column Name="IdAuxiliar" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TUsuario_TAuxiliar" Member="TUsuario" ThisKey="CodUsuario" OtherKey="CodUsuario" Type="TUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TDocente" Member="TDocente">
    <Type Name="TDocente">
      <Column Name="IdDocente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CodUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TUsuario_TDocente" Member="TUsuario" ThisKey="CodUsuario" OtherKey="CodUsuario" Type="TUsuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TUsuario" Member="TUsuario">
    <Type Name="TUsuario">
      <Column Name="CodUsuario" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.Data.Linq.Binary" DbType="VarBinary(8000) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="TUsuario_TAlumno" Member="TAlumno" ThisKey="CodUsuario" OtherKey="CodUsuario" Type="TAlumno" />
      <Association Name="TUsuario_TAuxiliar" Member="TAuxiliar" ThisKey="CodUsuario" OtherKey="CodUsuario" Type="TAuxiliar" />
      <Association Name="TUsuario_TDocente" Member="TDocente" ThisKey="CodUsuario" OtherKey="CodUsuario" Type="TDocente" />
    </Type>
  </Table>
</Database>